version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8.6-management
    hostname: "rabbitmq"
    ports:
      - 5672
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  test:
    image: ubuntu
    volumes:
      - ./bin/aws-mq-cli-dev:/bin/aws-mq-cli:ro
      - ./tests:/tests:ro
    working_dir: /
    environment:
      AMAZON_MQ_URI: amqp://rabbitmq:5672
      AMAZON_MQ_AUTH: user:password
    links:
      - rabbitmq
    tty: true
