#!/bin/bash

set -eu

gray=30
red=31
green=32
yellow=33
cyan=36

@colorize() {
  color=$1
  shift
  echo -e "\033[1;${color}m$@\033[0m"
}

run_file() {
  local path=$1
  local expected_stdout=${1%.*}.stdout
  local stdout=tmp/testing/stdout
  local stderr=tmp/testing/stderr

  rm -rf   tmp/testing
  mkdir -p tmp/testing

  if [[ "$path" =~ *\.sh ]]; then
    @colorize "$red" "Not shell scripts: [$path]"
    exit 1
  fi

  if [ ! -x "$path" ]; then
    @colorize "$red" "Not executable: [$path]"
    exit 2
  fi
  
  "$path" > "$stdout" 2>"$stderr"
  if cmp "$expected_stdout" "$stdout"; then
    @colorize "$green" "[OK] $path"
  else
    @colorize "$red" "[NG] $path"
    if [ -s "$stderr" ]; then
      cat "$stderr"
    else
      diff "$expected_stdout" "$stdout"
    fi
    exit 100
  fi
}

if [ $# -eq 0 ]; then
  echo "Usage: $0 [files]"
  exit
fi

for path in $@; do
  if [ -d "$path" ]; then
    for file in `find "$path" -name '*.sh'`; do
      run_file "$file" || exit $?
    done
  else
    run_file "$path" || exit $?
  fi
done
